# Generated by Django 2.1.1 on 2018-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
